### PR TITLE
Resolved home dir on Windows.

### PR DESCRIPTION
**Pull request by airportyh**
This fixes a bug on Windows which someone uncovered. If you'd like you can give me write access to the project and then I don't have to bother you with small fixes.

### CODE REVIEW

**Comment by dbrans** [comment]
This repo is deprecated
The most up-to-date code for the npm package lives at https://github.com/airportyh/browserstack-cli/
Thanks,
Derek

**Comment by airportyh** [comment]
@dbrans could you pull from my repo so that we are in sync (especially the README)? Because yours still has the google juice.

**Comment by dbrans** [comment]
Done.

**Comment by airportyh** [comment]
Thanks!

**Pull request closed without merging**
